### ISSUE TITLE
where your web-site gone?

### ISSUE THREAD

**Issue by xkcoding** [fastogt/fastoredis#86]
![image](https://user-images.githubusercontent.com/10429917/39680749-c11fe8c8-5169-11e8-95c1-c0de0e57409c.png)

**Comment by topilski** [comment]
Hi @xkcoding , now worked. Idon't know why it happens 1 hour ago.

**Comment by xkcoding** [comment]
still not working...@topilski

**Comment by topilski** [comment]
Working, please try by ip 138.68.252.92 or fastonosql.com

**Comment by topilski** [comment]
We have 2 sites, but it is very interesting why you can't see content.

**Comment by topilski** [comment]
Also you can try port 8080.

**Comment by topilski** [comment]
I fixed, thank you for notification.

**Comment by xkcoding** [comment]
80 port is still not working, i use 8080 fix it, thank you !

**Comment by topilski** [comment]
Thank you, for feedback, working for you!

**Comment by topilski** [comment]
80 port still not working? i checked availability here: https://www.uptrends.com/tools/uptime , where you placed?

**Comment by topilski** [comment]
Beijing - Shenzhen - Inner Mongolia - Heilongjiang Province - Yunnan Province -
This URL appears to be accessible from mainland China.

**Comment by topilski** [comment]
I think this sites checked nginx side, but issue will be in node.js.

**Comment by xkcoding** [comment]
https://fastonosql.com/ 
it works!!

**Comment by topilski** [comment]
Hi @xkcoding , can you help me, please notify me when you can to enter into fastoredis.com website, i wanna to check logs.

**Comment by xkcoding** [comment]
I‘m so sorry ... I went to a meeting then ... If you still want me to help you, please email me. 
email: shenyangkai1994@gmail.com
