### ISSUE TITLE
Not all keys showing in explorer tree

### ISSUE THREAD

**Issue by rickwargo** [fastogt/fastoredis#91]
After connecting to my Redis database (on AWS), I filter the keys using freqreg:2018122315* as a filter in "Load content of database", however, there is a key that does not show.

You can see in the screenshot it exists, and it did appear when I issued the KEYS command:

<img width="1271" alt="factoredis" src="https://user-images.githubusercontent.com/430137/50387731-b1a7b380-06d1-11e9-849d-3d51aceb7f4e.png">

**Comment by topilski** [comment]
Hi @rickwargo , i will try to reproduce, thank you for the issue.

**Comment by topilski** [comment]
Hi @rickwargo , i think i fixed this issue can you try new release to check it?

**Comment by rickwargo** [comment]
Still having issues displaying all the keys. Below is another example. Note it says only (2) keys but there are really 6.
![image](https://user-images.githubusercontent.com/430137/50551165-c4c70000-0c4a-11e9-8f95-9d334b1b8625.png)

**Comment by topilski** [comment]
I think i understand your issue, please load all keys 3000, because for tree we using scan command, but you check via KEYS. I think scan loaded only part of keys.

**Comment by rickwargo** [comment]
That makes sense. The 1000 limit is confusing here as I would expect them all to appear, but they won't. I like the treeview display, however, I do not think it represents the data accurately unless all data are read.

What about recursively descending each branch to completion instead of grabbing the next N (1000) keys? You may end up in a scenario where N' read is either < N or N' > N, but at least it is visually accurate, except for the last branch. That last branch could either be read to completion, possibly far over-reaching the original limit or it could be removed/not read, possibly under-reaching the limit. Additionally (or alternatively), you could inform the number of keys required to complete a branch.

I don't believe a treeview can be processed linearly; it can recursively traverse the tree.
